### ISSUE TITLE
SVG width="1" error "Failed parsing 'srcset' attribute value since its 'w' descriptor is invalid"

### ISSUE THREAD

**Issue by djcowan** [ResponsiveImagesCG/wp-tevko-responsive-images#133] opened 2015-06-11 07:07 UTC
SVG images return errors as they have a WordPress defined width and height of "1".
Technically this issue is not relevant to this wonderful plugin, as WordPress Core does not support, and it appears has no intention of supporting the SVG format.
`https://core.trac.wordpress.org/ticket/26256`
But I am interested in suggestions and thoughts on the issue.
Details:
The SVG files have been uploaded into the WP media library.
They are returned via the WordPress wp_get_attachment_image function
`https://codex.wordpress.org/Function_Reference/wp_get_attachment_image`
I'd love to get some thought on a workaround, but have no expectations, as we are currently rewriting the code to use an alternative WP function.

**Comment by joemcgill** [comment] 2015-06-11 22:44
That's interesting. I assume that error message came from a browser or markup validator and not from WordPress, correct? Or am I misunderstanding. If _any_ 1px wide images produce the same result than we could handle this internally. If it's particular to SVGs, I would think you would need to add your own filters to `image_send_to_editor` and `wp_get_attachment_image_attributes` which check for the file's mime type, and if it's SVG, disable our filters.

You could also hook into the `image_downsize` filter and either return false or a width of zero if the image is an SVG. But those options might have other unintended consequences.

**Comment by djcowan** [comment] 2015-06-12 23:39
Correct, the error message came from the browser inspector. We played with a few functions including some of those mentioned. 
`image_downsize`… ` wp_get_attachment_image_attributes`… `wp_get_attachment_metadata `
Currently we are conditionally checking for width or height less than or equal to one… its fairly dirty but the work around is working fine. Just read thread #129 :
`Added check to make sure there's more than one image size. #129'
Which might just resolve the issue? Thanks for the prompt reply to m initial question, and thanks for developing the plugin; it is extremely useful and is a great solution to what has been a problem for us for some time.

**Comment by jaspermdegroot** [comment] 2015-08-24 16:27
I wonder if https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/commit/c463c9060b3318e775ca90efb2c893abc5ca6814 and https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/commit/566d9ac249124e799c987879dc4a5c916f9ebcb5 already fixed this issue.

https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/commit/c463c9060b3318e775ca90efb2c893abc5ca6814 did fix https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/issues/153 which was also about warnings when using SVG images, but I am not sure if @djcowan is getting the same warnings.

@djcowan those two commits are merged in the dev branch. Maybe you can test by replacing the content of your wp-tevko-responsive-images.php file by the content of https://raw.githubusercontent.com/ResponsiveImagesCG/wp-tevko-responsive-images/dev/wp-tevko-responsive-images.php

**Comment by joemcgill** [comment] 2015-08-24 16:40
I was thinking the same thing, that this seemed to be a duplicate of #153.

**Comment by tevko** [comment] 2015-08-25 02:42
Closed in https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/pull/154

**Closed by tevko** 2015-08-25 02:42 UTC
Labels: bug

**Comment by djcowan** [comment] 2015-09-02 08:37
Awesome! Version 2.4 fixed the SVG issue :)

**Comment by joemcgill** [comment] 2015-09-02 11:49
Thanks for the report @djcowan.
