### ISSUE TITLE
Filter for custom default sizes attribute deactivates the function to insert images

### ISSUE THREAD

**Issue by solemone** [ResponsiveImagesCG/wp-tevko-responsive-images#168] opened 2015-09-03 14:33 UTC
Hi,
I am using the filter to add a custom default `sizes` attribute as described in #130. But when I try to insert an image nothing happens. Really nothing, no image is send to editor. I use the this code in my functions.php:
```
add_filter( 'tevkori_image_sizes_args', 'my_custom_sizes' );
function my_custom_sizes( $args, $id, $size ) {
    if ( $size == 'full' ) {
        $args['sizes'] = '(min-width: 70rem) 53vw, (min-width: 64rem) 80vw, calc(100vw - 3em)';
    }
    return $args;
}
```
WordPress 4.3 and RICG Responsive Images 2.4.0

Am I doing something wrong?

Thanks,
Ivo

**Comment by joemcgill** [comment] 2015-09-04 02:26
Hi @solemone, I've added your code to a clean version of a site running the TwentyFifteen theme and version 2.4.0 of the RICG plugin and I'm not able to reproduce the issue. Can you try disabling other plugins to make sure nothing else is conflicting with our plugin?

**Comment by solemone** [comment] 2015-09-10 13:13
Hi Joe,
thanks for your fast reply. I’ve disabled all other plugins and removed all other code from my functions.php except for the tevkori_image_sizes_args filter and add_image_size(). Unfortunately, nothing has changed—on my hosting and my local server.

In my local develop environment I get two warnings if I’ve added a featured image. This warnings appear at the “Featured Image” box:

Warning: Missing argument 2 for my_custom_sizes() in /url/to/my/functions.php on line 63
Warning: Missing argument 3 for my_custom_sizes() in  /url/to/my/functions.php on line 63

Is it because the my_custom_sizes() function does not return $id and $size?

I’ve also installed a new WordPress system running the TwentyFifteen theme with no other plugins but it is the same problem. If the tevkori_image_sizes_args filter is uncommented everything works great at all installations.

I would appreciate your help very much. Thanks,
Ivo

**Comment by joemcgill** [comment] 2015-09-11 11:43
Hi @solemone, 

`my_custom_sizes()` is not a function from the plugin, so I'm not exactly sure what's causing the error. Could you paste in the code from your `function.php` where `my_custom_sizes` is defined? That would help me determine if there's a conflict with the plugin or not.

**Comment by joemcgill** [comment] 2015-09-11 11:48
Hi @solemone,

I'm wondering if you're actually calling that same function as the part of another filter. I've seen several examples where a custom function named `my_custom_sizes`. Could you try renaming the function to something else just to make sure that's not the case?

**Comment by solemone** [comment] 2015-09-16 21:24
Hi Joe,
I’ve renamed the `my_custom_sizes` function, but nothing has changed. As I described above, I’ve disabled all other plugins and removed all other code from my functions.php.

Can you make something of the PHP warnings?

**Comment by joemcgill** [comment] 2015-09-17 01:31
Oh, my mistake. By default, `add_filter()` will only pass the variable being filtered to your callback function. In order to pass all three parameters you will need to do this:

```
add_filter( 'tevkori_image_sizes_args', 'my_custom_sizes', 10 , 3 );
```

See: https://codex.wordpress.org/Function_Reference/add_filter

**Comment by solemone** [comment] 2015-09-17 12:27
Hi Joe,
now it’s working. Thank you very much.
Ivo

**Comment by jaspermdegroot** [comment] 2015-09-17 13:04
Closing as resolved.

**Closed by jaspermdegroot** 2015-09-17 13:04 UTC
