### ISSUE TITLE
Conflict with Woocommerce Product variations

### ISSUE THREAD

**Issue by mantismamita** [ResponsiveImagesCG/wp-tevko-responsive-images#139] opened 2015-06-19 07:04 UTC
Here is an example of the desired behaviour :http://demo.woothemes.com/?name=canvas

The colour of the main image should change on select (in this case from Black to Green). Activating RICG prevents this from happening. Dequeuing the picturefill script from the page in question has no effect.

**Comment by jaspermdegroot** [comment] 2015-06-19 10:08
@mantismamita 

All pages in that demo use the same url so I am not sure what image on what page you were looking at. Do you mean that on a single product template the large product image doesn't change when you select a different variation?
For example; in case of product "Ship Your Idea" when you select color green, you still see the image of the black t-shirt instead of the green one?
Do you see an error in the console?

**Comment by mantismamita** [comment] 2015-06-19 10:13
Ah sorry the url doesn't update on their demo. Yes, that's the one. No js errors and if I remove the script it still happens.

**Comment by jaspermdegroot** [comment] 2015-06-20 09:55
The Picturefill script only make things work on browsers that don't support ```srcset``` and ```sizes``` yet. On what browser are you testing?

If the RICG plugin is causing an issue it's probably more because of the changes it makes in the markup.
Here is the markup of main product image on the "Ship Your Idea" product page without RICG plugin:

```
<img width="470" height="470" src="http://demo.woothemes.com/canvas/files/2013/06/T_4_front-470x470.jpg" class="attachment-shop_single wp-post-image" alt="T_4_front" title="T_4_front">
```

When selecting the green color, the JS of the theme changes the markup to:

```
<img width="470" height="470" src="http://demo.woothemes.com/canvas/files/2013/06/T_3_front-470x470.jpg" class="attachment-shop_single wp-post-image" alt="" title="T_3_front" data-o_src="http://demo.woothemes.com/canvas/files/2013/06/T_4_front-470x470.jpg" data-o_title="T_4_front" data-o_alt="T_4_front">
```

Now the image of the green t-shirt is shown so everything works fine.

I can't test that theme with the RICG plugin so can you copy the image markup from your code inspector and paste it in a comment here?

**Comment by mantismamita** [comment] 2015-06-20 20:17
Yes, I'm testing in Chrome so no need for picturefill but i thought it would be good to rule that out.

Here is the markup without the plugin active. I have a lamp with a cream shade and when I select Black Shade the markup changes to:

    <a href="http://mysite.com/wp- content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-black.jpg" itemprop="image" class="woocommerce-main-image zoom" title="6004-SAGE Mid century modern cascading orbs with black drum shade" data-rel="prettyPhoto[product-gallery]" data-o_href="http://mysite.com/wp-content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-cream.jpg">
    <img width="400" height="400" src="http://mysite.com/wp-content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-black-400x400.jpg" class="attachment-shop_single wp-post-image" alt="6004-SAGE Mid century modern cascading orbs with black drum shade" title="6004-SAGE Mid century modern cascading orbs with black drum shade" data-o_src="http://mysite.com/wp-content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-cream-400x400.jpg" data-o_title="6004-SAGE Mid century modern cascading orbs with ceam drum shade" data-o_alt="6004-SAGE Mid century modern cascading orbs with ceam drum shade">
    <img width="400" height="400" src="http://mysite.com/wp-content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-black-400x400.jpg" class="attachment-shop_single wp-post-image" alt="6004-SAGE Mid century modern cascading orbs with black drum shade" title="6004-SAGE Mid century modern cascading orbs with black drum shade" data-o_src="http://mysite.com/wp-content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-cream-400x400.jpg" data-o_title="6004-SAGE Mid century modern cascading orbs with ceam drum shade" data-o_alt="6004-SAGE Mid century modern cascading orbs with ceam drum shade">
    </a>

And with the RICG plugin activated. The markup also changes to the black shade but the image stays the same :

    <a href="http://mysite.com/wp-content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-black.jpg" itemprop="image" class="woocommerce-main-image zoom" title="6004SAGE-cascading-orbs.cutout.drum-shade-black" data-rel="prettyPhoto[product-gallery]" data-o_href="http://mysite.com/wp-content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-cream.jpg">
     <img width="400" height="400" src="http://mysite.com/wp-content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-black-400x400.jpg" class="attachment-shop_single wp-post-image" alt="" title="6004SAGE-cascading-orbs.cutout.drum-shade-black" sizes="(max-width: 400px) 100vw, 400px" srcset="http://mysite.com/wp-content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-cream-150x150.jpg 150w, http://mysite.com/wp-content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-cream-300x300.jpg 300w, http://mysite.com/wp-content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-cream-450x450.jpg 450w, http://mysite.com/wp-content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-cream-320x320.jpg 320w, http://mysite.com/wp-content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-cream-400x400.jpg 400w, http://mysite.com/wp-content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-cream.jpg 3000w" data-o_src="http://mysite.com/wp-content/uploads/2015/06/6004SAGE-cascading-orbs.cutout.drum-shade-cream-400x400.jpg" data-o_title="6004SAGE-cascading-orbs.cutout.drum-shade-cream" data-o_alt="6004SAGE-cascading-orbs.cutout.drum-shade-cream">
    </a>

I was just using the demo site as an example but nothing happens (no broken image) so in the case of the demo it would remain the black shirt.

**Comment by jaspermdegroot** [comment] 2015-07-14 10:46
@mantismamita 

Thanks for the markup and sorry for my late reply. I looked into this again and it became clear what the problem is.

When you select a different color the theme uses JavaScript to change the value of the ```src``` attribute to the image that corresponds to the selected color. However, with responsive images the ```src``` attribute doesn't matter anymore because ```srcset``` is used instead. The theme script doesn't update the value of this attribute. That's why you don't get to see a different image. This plugin is never requested to generate markup for the images of the other color variations, so this is not a bug in or something we can fix with this plugin.

@joemcgill @tevko - Can one of you close this ticket as not a bug? Thanks!

**Comment by tevko** [comment] 2015-07-14 13:57
@jaspermdegroot thanks for being amazing

**Closed by tevko** 2015-07-14 13:57 UTC
