### ISSUE TITLE
Problem with WooCommerce images

### ISSUE THREAD

**Issue by thisisbbc** [ResponsiveImagesCG/wp-tevko-responsive-images#266] opened 2015-12-10 20:20 UTC
Hi there,

Since WP4.4 our product images are not displaying appropriately and are being cropped. I've read quite a bit on the changes related to responsive images but I'm still not too sure how the whole thing works and how to alter its behavior.

We're supposed to have square images and so far I haven't been able to fix this.

Any help would be appreciated!

URL : http://goo.gl/zhzIV9

Regards,
B

**Comment by jaspermdegroot** [comment] 2015-12-10 23:46
@thisisbbc 

What page exactly should we look and on what device and browser do you experience the problem? I just checked on a MacBook with Retina screen in Chrome browser and I do see square images in your shop.
Since you're not using the plugin but notice the problem with WordPress core it's probably better to open a ticket in the WordPress issue tracker.

Off topic: Whatever script your site is using to speed up scrolling ... it's killing your site. I can't scroll your pages normally with the trackpad on my Mac.

**Comment by thisisbbc** [comment] 2015-12-11 00:13
@jaspermdegroot thanks a lot for the quick reply. I've been experiencing the problem on all single-product pages on desktop with Chrome v47.0.2526.73m and v47.0.2526.80m. I'm also able to replicate the issue using Edge. Firefox and Safari however does load a square image.

It's definitely a good idea to submit the issue in the WP trac so I'll do that right now.

Also thank you a lot for pointing out the problem with our scrolling script. Since I don't have a mac around it's hard for me to test this platform. The module was included in Ultimate Addons for Visual Composer. I have deactivated it to put back an older smooth scroll library, hopefully it'll fix the issue with the trackpad.

Kind regards,
B

**Comment by joemcgill** [comment] 2015-12-11 04:56
Hi @thisisbbc,

Thanks for reaching out. I commented on your report in the [WP.org repo](https://wordpress.org/support/topic/woocommerce-images-are-cropped?replies=2) and it looks like there may be another plugin or something in play that is affecting the image markup. The issue you're experiencing is happening because there is an image in the `srcset` that shouldn't be there, but there are also various `data-` attributes being added as well, which makes me think something else might be in play.

If this issue is still reproducible after turning off plugins and switching to a default theme, then it would be interesting to see what is saved in the attachment metadata for those images, (e.g., the output of `wp_get_attachment_metadata`).

Thanks,
Joe

**Comment by joemcgill** [comment] 2015-12-11 05:08
Looks like you reported the issue on the [WordPress Trac](https://core.trac.wordpress.org/ticket/34998#comment:1) as well, which is probably the best place to resolve this issue, so I'm going to close this for now and we can move discussion over there.

**Closed by joemcgill** 2015-12-11 05:08 UTC
